// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// WHInter
Rcpp::List WHInter(arma::sp_mat& mat, std::vector<double>& Y, int nlambda, double lambdaMinRatio, int maxSelectedFeatures, bool useBias, int useMyMips, int typeBound, int F, double eps);
RcppExport SEXP _WHInter_WHInter(SEXP matSEXP, SEXP YSEXP, SEXP nlambdaSEXP, SEXP lambdaMinRatioSEXP, SEXP maxSelectedFeaturesSEXP, SEXP useBiasSEXP, SEXP useMyMipsSEXP, SEXP typeBoundSEXP, SEXP FSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambdaMinRatio(lambdaMinRatioSEXP);
    Rcpp::traits::input_parameter< int >::type maxSelectedFeatures(maxSelectedFeaturesSEXP);
    Rcpp::traits::input_parameter< bool >::type useBias(useBiasSEXP);
    Rcpp::traits::input_parameter< int >::type useMyMips(useMyMipsSEXP);
    Rcpp::traits::input_parameter< int >::type typeBound(typeBoundSEXP);
    Rcpp::traits::input_parameter< int >::type F(FSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(WHInter(mat, Y, nlambda, lambdaMinRatio, maxSelectedFeatures, useBias, useMyMips, typeBound, F, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WHInter_WHInter", (DL_FUNC) &_WHInter_WHInter, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_WHInter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
