# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WHInter <- function(mat, Y, nlambda = 100L, lambdaMinRatio = 0.01, maxSelectedFeatures = 150L, useBias = 1L, useMyMips = 2L, typeBound = 2L, F = 50L, eps = 1e-8) {
    .Call(`_WHInter_WHInter`, mat, Y, nlambda, lambdaMinRatio, maxSelectedFeatures, useBias, useMyMips, typeBound, F, eps)
}

